#rabbitmq-data:
#  image: rabbitmq:3.6.6
#  container_name: rabbitmq-data
#  tty: true
#  command: chown -v -R 999:999 /var/lib/rabbitmq
#  volumes:
#  - './build/docker/var/lib/rabbitmq:/var/lib/rabbitmq'
#  - './build/docker/etc/rabbitmq:/etc/rabbitmq'
#  stdin_open: true
rabbitmq:
  image: rabbitmq:3.6.6
  container_name: rabbitmq
  hostname: rabbitmq
  environment:
    RABBITMQ_DEFAULT_USER: twitter
    RABBITMQ_DEFAULT_PASS: twitter
  ports:
  - '5672:5672'
##  volumes_from:
##  - rabbitmq-data
#  volumes:
#  - './build/docker/var/lib/rabbitmq:/var/lib/rabbitmq'
#  - './build/docker/etc/rabbitmq:/etc/rabbitmq'
mongodb:
  container_name: mongodb
  image: mongo:3.0.14
  environment:
    MONGO_PORT_27017_TCP_ADDR: mongodb
    MONGO_PORT_27017_TCP_PORT: 27017
  ports:
  - '27017:27017'
#  volumes:
#  - './build/docker/data/db:/data/db'
