## http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html

#ribbon.eureka.enabled: false
zuul:
  ignoredServices: '*'
  routes:
    tweet-query:
      path: /tweet-query/**
      serviceId: tweet-query
      stripPrefix: false
    webflux:
      path: /webflux/**
      url: http://localhost:8000
