spring:
  mvc.favicon.enabled: false
  resources.cachePeriod: 3600
server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/javascript
      - application/json
      - text/javascript
      - text/plain
      - text/html
      - text/xml
      - text/css
http:
  gzip:
    deflate-compression-level: 5
    methods: GET,POST,PUT,DELETE
    mime-types: ${app.gzip.types}
    min-gzip-size: ${app.gzip.size}
