server:
  port: 8000
spring:
  rabbitmq:
    username: twitter
    password: twitter
  cloud:
    stream:
      bindings:
        input:
          content-type: application/json
          durableSubscription: true
          destination: twitter
          group: tweeter
        output:
          content-type: application/json
          destination: twitter
          group: tweeter
